### ISSUE TITLE
introduction

### ISSUE THREAD

**Issue by sebuls** [mug896/sed-stream-editor#2]
https://mug896.github.io/sed-stream-editor/index.html
처음에 나오는 책 그림은 Stream EDitor 라고 나와서 번역본인가 생각했습니다.
번역했다면 원저자는 누구인지 알려주시면 좋겠습니다.
번역본 아니라면 처음 나오는 책 그림에 영어만 쓰지 말고 한글도 쓰면 좋겠습니다.

**Comment by mug896** [comment]
쉘에서 명령을 실행할 때 영문으로 타입 하기 때문에 타이틀도 영문으로 적고 있습니다.
번역본은 아니고 제가 명령을 사용하면서 필요하다고 생각되는 점들을 모아서 만들고 있습니다.
