### ISSUE TITLE
3. Addresses typo report

### ISSUE THREAD

**Issue by gyute** [mug896/sed-stream-editor#3]
안녕하세요!😄 
예제 2 solution에서 [shovel]헤더의 escape가 빠진 것 같습니다!
`$ sed '/[shovel]/,/^$/ s/enabled = 0/enabled = 1/' file`
↓
`$ sed '/\[shovel]/,/^$/ s/enabled = 0/enabled = 1/' file`

**Comment by mug896** [comment]
넵!
